version: '3'
services:
    arch:
        build: .
        image: viviridian/archbeets
        container_name: archbeets
        hostname: arch_beets
        volumes:
          #- ./launch.sh:/launch.sh:ro
          #- ./user_launch.sh:/user_launch.sh:ro
          - /home/vivlim/.ssh:/home/vivlim/.ssh:ro
          - /home/vivlim:/home/vivlim/external:ro
          - /mnt/big:/home/vivlim/big:ro
          #- home:/home/vivlim
          - ssh_server_keys:/etc/ssh/keys
        restart: unless-stopped
        ports:
          - "8322:22"

volumes:
    ssh_server_keys:
    home:
