version: '3.2'
services:
    arch:
        build: .
        image: viviridian/archbeets
        container_name: archbeets
        hostname: arch_beets
        volumes:
          #- ./launch.sh:/launch.sh:ro
          #- ./user_launch.sh:/user_launch.sh:ro
          - /home/vivlim/.ssh:/home/vivlim/.ssh:ro
          - /home/vivlim:/home/vivlim/external:ro
          - /mnt/big:/home/vivlim/big:ro
          - /mnt/big/vivlim/beets-library:/home/vivlim/music
          - ./beets:/home/vivlim/.config/beets
          - home:/home/vivlim
          - ssh_server_keys:/etc/ssh/keys
          - 
            type: bind
            source: "/net/192.168.1.107/depths"
            target: "/home/vivlim/depths"
            read_only: true
            bind:
                propagation: rshared
        restart: unless-stopped
        ports:
          - "8322:22"
        networks:
          - frontend
    ampache:
        image: jgoerzen/ampache-mysql
        container_name: ampache
        tty: true
        networks:
          - frontend
        tmpfs:
          - /run:size=100M
          - /run/lock:size=100M
        stop_signal: SIGRTMIN+3
        volumes:
          - /sys/fs/cgroup:/sys/fs/cgroup:ro
          - /mnt/big/vivlim/beets-library:/music:ro
          - /mnt/big/vivlim/playlists:/playlists:rw
          - ./ampache_config:/var/www/html/ampache/config:rw
          - ./ampache_apache2.conf:/etc/apache2/apache2.conf:ro
          - ampache_mysql:/var/lib/mysql:rw
        restart: unless-stopped
        ports:
          - "8932:80"
        environment:
          - DEBBASE_NO_STARTUP_APT=yes
    supysonic:
      image: 'speranza/supysonic-pg'
      container_name: 'supysonic'
      restart: 'unless-stopped'
      networks:
        - frontend
        - backend
      environment:
        - PUID=1000
        - PGID=1000
      volumes:
        - './supysonic.conf:/etc/supysonic'
        - '/mnt/big/vivlim/beets-library:/media'
      ports:
        - 8000:8000
    postgres:
      image: postgres:10.5
      container_name: supysonic_postgres
      hostname: supysonic_postgres
      restart: always
      networks:
        - backend
      volumes:
        - ./supysonic_pg/data:/var/lib/postgresql/data
        - ./supysonic_pg/postgres.conf:/etc/postgres.conf
        - ./supysonic_pg/pg_hba.conf:/etc/pg_hba.conf
      command: postgres -c config_file=/etc/postgres.conf
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres

volumes:
    ssh_server_keys:
    home:
    ampache_mysql:

networks:
    frontend:
        external:
            name: ingress_frontend
    backend:
